# This workflow will build a golang project on every pull request and will build and publish a container package on every release or tag creation

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  tags:
  - '*'
  release:
    types: [created]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Go build
      run: go build -v ./...
   
  build_and_publish_container_package:
    if: $GITHUB_REF == "ref/tags/*.*.*"
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Docker login
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME_GITHUB }}
        password: ${{ secrets.DOCKER_PASSWORD_GITHUB }}

    - name: Catch git tag for container image tag
      run: slice=$(echo "/ref/tags/v1.0.0" | cut -d '/' -f 4) 
      env:
       tag: $slice
      
    - name: Build docker image
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: ghcr.io/qumber-ali/secret-loader:$tag   


